from ..common.types import (
    AccountIdShape,
    AddAccountNoteDirective,
    AddressDetails,
    AmendScheduleDirective,
    anyObject,
    Balance,
    BalanceDefaultDict,
    BalanceTimeseries,
    calendarObject,
    CalendarEvent,
    CalendarEvents,
    callableObject,
    ClientTransaction,
    ClientTransactionEffects,
    ClientTransactionEffectsDefaultDict,
    DateShape,
    datetimeObject,
    decimalObject,
    defaultAddress,
    defaultAsset,
    defaultDict,
    defaultDictObject,
    DenominationShape,
    dictObject,
    EventTypesGroup,
    EventTypeSchedule,
    Features,
    FlagTimeseries,
    HookDirectives,
    InvalidContractParameter,
    iterableObject,
    iteratorObject,
    jsonDumpsObject,
    jsonLoadsObject,
    Level,
    listObject,
    mappingObject,
    mathObject,
    namedTupleObject,
    newTypeObject,
    noReturnObject,
    NoteType,
    NumberKind,
    NumberShape,
    optionalObject,
    OptionalShape,
    OptionalValue,
    Parameter,
    ParameterTimeseries,
    parseToDatetimeObject,
    Phase,
    PostingInstruction,
    PostingInstructionBatch,
    PostingInstructionBatchDirective,
    PostingInstructionType,
    Rejected,
    RejectedReason,
    RemoveSchedulesDirective,
    ROUND_05UP,
    ROUND_CEILING,
    ROUND_DOWN,
    ROUND_HALF_EVEN,
    roundFloorObject,
    roundHalfDownObject,
    roundHalfUpObject,
    setObject,
    StringShape,
    timedeltaObject,
    transaction_reference_field_name,
    TransactionCode,
    Tside,
    tupleObject,
    typeObject,
    UnionItem,
    UnionItemValue,
    unionObject,
    UnionShape,
    UpdateAccountEventTypeDirective,
    UpdatePermission,
    WorkflowStartDirective,
)


def types_registry():
    return {
        "AccountIdShape": AccountIdShape,
        "AddAccountNoteDirective": AddAccountNoteDirective,
        "AddressDetails": AddressDetails,
        "AmendScheduleDirective": AmendScheduleDirective,
        "Any": anyObject,
        "Balance": Balance,
        "BalanceDefaultDict": BalanceDefaultDict,
        "BalanceTimeseries": BalanceTimeseries,
        "calendar": calendarObject,
        "CalendarEvent": CalendarEvent,
        "CalendarEvents": CalendarEvents,
        "Callable": callableObject,
        "ClientTransaction": ClientTransaction,
        "ClientTransactionEffects": ClientTransactionEffects,
        "ClientTransactionEffectsDefaultDict": ClientTransactionEffectsDefaultDict,
        "DateShape": DateShape,
        "datetime": datetimeObject,
        "Decimal": decimalObject,
        "DEFAULT_ADDRESS": defaultAddress,
        "DEFAULT_ASSET": defaultAsset,
        "defaultdict": defaultDict,
        "DefaultDict": defaultDictObject,
        "DenominationShape": DenominationShape,
        "Dict": dictObject,
        "EventTypesGroup": EventTypesGroup,
        "EventTypeSchedule": EventTypeSchedule,
        "Features": Features,
        "FlagTimeseries": FlagTimeseries,
        "HookDirectives": HookDirectives,
        "InvalidContractParameter": InvalidContractParameter,
        "Iterable": iterableObject,
        "Iterator": iteratorObject,
        "json_dumps": jsonDumpsObject,
        "json_loads": jsonLoadsObject,
        "Level": Level,
        "List": listObject,
        "Mapping": mappingObject,
        "math": mathObject,
        "NamedTuple": namedTupleObject,
        "NewType": newTypeObject,
        "NoReturn": noReturnObject,
        "NoteType": NoteType,
        "NumberKind": NumberKind,
        "NumberShape": NumberShape,
        "Optional": optionalObject,
        "OptionalShape": OptionalShape,
        "OptionalValue": OptionalValue,
        "Parameter": Parameter,
        "ParameterTimeseries": ParameterTimeseries,
        "parse_to_datetime": parseToDatetimeObject,
        "Phase": Phase,
        "PostingInstruction": PostingInstruction,
        "PostingInstructionBatch": PostingInstructionBatch,
        "PostingInstructionBatchDirective": PostingInstructionBatchDirective,
        "PostingInstructionType": PostingInstructionType,
        "Rejected": Rejected,
        "RejectedReason": RejectedReason,
        "RemoveSchedulesDirective": RemoveSchedulesDirective,
        "ROUND_05UP": ROUND_05UP,
        "ROUND_CEILING": ROUND_CEILING,
        "ROUND_DOWN": ROUND_DOWN,
        "ROUND_FLOOR": roundFloorObject,
        "ROUND_HALF_DOWN": roundHalfDownObject,
        "ROUND_HALF_EVEN": ROUND_HALF_EVEN,
        "ROUND_HALF_UP": roundHalfUpObject,
        "Set": setObject,
        "StringShape": StringShape,
        "timedelta": timedeltaObject,
        "TRANSACTION_REFERENCE_FIELD_NAME": transaction_reference_field_name,
        "TransactionCode": TransactionCode,
        "Tside": Tside,
        "Tuple": tupleObject,
        "Type": typeObject,
        "Union": unionObject,
        "UnionItem": UnionItem,
        "UnionItemValue": UnionItemValue,
        "UnionShape": UnionShape,
        "UpdateAccountEventTypeDirective": UpdateAccountEventTypeDirective,
        "UpdatePermission": UpdatePermission,
        "WorkflowStartDirective": WorkflowStartDirective,
    }
