name: Code Quality

on: pull_request

jobs:
  super-lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run super-linter
        run: |
            python3 -m flake8 . --exclude=contracts_sdk

